#!/bin/csh

echo "+++ Reconfiguring scantool"
( cd scantool ; ./reconf )

echo "+++ Reconfiguring scangui"
# Kludge - because I can't get CVS to change the permissions.
chmod ug+x scangui/reconf scangui/install
( cd scangui ; ./reconf )

echo "+++ Running Makefile"
make

